### ISSUE TITLE
requeue icon inconsistency

### ISSUE THREAD

**Issue by aruld** [cptn-io/el-cptn#80]
Should the icon match for requeue under Actions?

<img width="1305" alt="Screenshot 2023-05-18 at 10 15 43 PM" src="https://github.com/cptn-io/el-cptn/assets/442380/1dc192dd-6432-438a-9898-d10e0f621ba7">

**Comment by kcthota** [comment]
Thanks for logging the issue. Definitely some inconsistent icons in few places. 

- I have used the same icon for resend/requeue between incoming and outgoing events. _Requeue now consistently uses Bolt icon._
- Requeue failed used a variant of refresh icon. _It's now changed to use Bolt icon similar to requeue event action._
- Positioning of refresh and requeue between the row and the top area is different. _Switched the position of buttons so they are both consistent._


<img width="814" alt="Screenshot 2023-05-18 at 11 34 52 PM" src="https://github.com/cptn-io/el-cptn/assets/2999820/c716c42d-92b2-4847-abcb-0f8a5bd27cef">

**Comment by aruld** [comment]
Perfect, looks great!
